=== RainerJava/smart-cms/content-api-impl/src/main/resources/com/smartitengineering/cms/content/content-type-schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
 *
 * This is a simple Content Management System (CMS)
 * Copyright (C) 2009  Imran M Yousuf (imyousuf@smartitengineering.com)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
xmlns="http://www.smartitengineering.com/smart-cms/content/content-type-schema"
targetNamespace="http://www.smartitengineering.com/smart-cms/content/content-type-schema"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.w3.org/2001/XMLSchema http://www.w3.org/2001/XMLSchema.xsd"
>
  <xs:simpleType name="smartDate">
    <xs:restriction base="xs:dateTime">
      <xs:pattern value="[1-9][0-9]{3}-[0-9]{2}-[0-9]{2}T[0-2][0-9]:[0-5][0-9]:[0-5][0-9]([+-][0-2][0-9]:[0-5][0-9])"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:element name="mimeType" type="xs:string" />
  <xs:element name="name" type="xs:string" />
  <xs:element name="typeNS" type="xs:string" />
  <xs:element name="typeName" type="xs:string" />
  <xs:element name="bidirectional" type="xs:string" />
  <xs:group name="contentTypeGrp">
    <xs:sequence>
      <xs:element ref="typeNS" minOccurs="1" maxOccurs="1" />
      <xs:element ref="typeName" minOccurs="1" maxOccurs="1" />
    </xs:sequence>
  </xs:group>
  <xs:element name="content">
    <xs:complexType>
      <xs:sequence>
        <xs:group ref="contentTypeGrp" minOccurs="1" maxOccurs="1" />
        <xs:element ref="bidirectional" minOccurs="0" maxOccurs="1" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="long" />
  <xs:element name="integer" />
  <xs:element name="double" />
  <xs:element name="boolean" />
  <xs:element name="datetime" type="smartDate" />
  <xs:element name="encoding" type="xs:string" />
  <xs:element name="string">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="mimeType" minOccurs="1" maxOccurs="1"/>
        <xs:element ref="encoding" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="other">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="mimeType" minOccurs="1" maxOccurs="1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="size" type="xs:integer" />
  <xs:element name="collection">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="simple-value" minOccurs="1" maxOccurs="1"/>
        <xs:element ref="size" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="value">
    <xs:complexType>
      <xs:sequence>
        <xs:choice>
          <xs:element ref="content" minOccurs="1" maxOccurs="1" />
          <xs:element ref="long" minOccurs="1" maxOccurs="1" />
          <xs:element ref="integer" minOccurs="1" maxOccurs="1" />
          <xs:element ref="double" minOccurs="1" maxOccurs="1" />
          <xs:element ref="boolean" minOccurs="1" maxOccurs="1" />
          <xs:element ref="datetime" minOccurs="1" maxOccurs="1" />
          <xs:element ref="string" minOccurs="1" maxOccurs="1" />
          <xs:element ref="other" minOccurs="1" maxOccurs="1" />
          <xs:element ref="collection" minOccurs="1" maxOccurs="1" />
        </xs:choice>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="simple-value">
    <xs:complexType>
      <xs:sequence>
        <xs:choice>
          <xs:element ref="content" minOccurs="1" maxOccurs="1" />
          <xs:element ref="long" minOccurs="1" maxOccurs="1" />
          <xs:element ref="integer" minOccurs="1" maxOccurs="1" />
          <xs:element ref="double" minOccurs="1" maxOccurs="1" />
          <xs:element ref="boolean" minOccurs="1" maxOccurs="1" />
          <xs:element ref="datetime" minOccurs="1" maxOccurs="1" />
          <xs:element ref="string" minOccurs="1" maxOccurs="1" />
          <xs:element ref="other" minOccurs="1" maxOccurs="1" />
        </xs:choice>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="required" type="xs:boolean" />
  <xs:element name="internal">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name" minOccurs="1" maxOccurs="1" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="external" type="xs:string" />
  <xs:element name="uri">
    <xs:complexType>
      <xs:sequence>
        <xs:choice>
          <xs:element ref="internal" minOccurs="1" maxOccurs="1" />
          <xs:element ref="external" minOccurs="1" maxOccurs="1" />
        </xs:choice>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="templateType">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:enumeration value="velocity" />
        <xs:enumeration value="ruby" />
        <xs:enumeration value="javascript" />
        <xs:enumeration value="groovy" />
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:complexType name="resource">
    <xs:sequence>
      <xs:element ref="name" minOccurs="1" maxOccurs="1" />
      <xs:element ref="mimeType" minOccurs="1" maxOccurs="1" />
      <xs:element ref="templateType" minOccurs="1" maxOccurs="1" />
      <xs:element ref="uri" minOccurs="1" maxOccurs="1" />
    </xs:sequence>
  </xs:complexType>
  <xs:element name="variation" type="resource" />
  <xs:element name="representation" type="resource" />
  <xs:element name="representations">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="representation" minOccurs="1" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="variations">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="variation" minOccurs="1" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="field">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name" minOccurs="1" maxOccurs="1"/>
        <xs:element ref="value" minOccurs="1" maxOccurs="1"/>
        <xs:element ref="required" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="variations" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="fields">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="field" minOccurs="1" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="parentTypeNS" type="xs:string" />
  <xs:element name="parentTypeName" type="xs:string" />
  <xs:group name="parentType">
    <xs:sequence>
      <xs:element ref="parentTypeNS" minOccurs="1" maxOccurs="1" />
      <xs:element ref="parentTypeName" minOccurs="1" maxOccurs="1" />
    </xs:sequence>
  </xs:group>
  <xs:element name="statusName" type="xs:string" />
  <xs:element name="status">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="statusName" minOccurs="1" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="contentType">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name" minOccurs="1" maxOccurs="1" />
        <xs:group ref="parentType" minOccurs="0" maxOccurs="1" />
        <xs:element ref="fields" minOccurs="1" />
        <xs:element ref="status" minOccurs="1" maxOccurs="1" />
        <xs:element ref="representations" minOccurs="0" maxOccurs="1" />
      </xs:sequence>
      <xs:attribute name="namespace" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>
  <xs:element name="contentTypes">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="contentType" minOccurs="1" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== RainerJava/smart-cms/content-api-impl/src/test/resources/content-type-def-1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
 *
 * This is a simple Content Management System (CMS)
 * Copyright (C) 2009  Imran M Yousuf (imyousuf@smartitengineering.com)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->
<!--
    Document   : content-type-def-1.xml
    Created on : September 25, 2009, 1:10 PM
    Author     : imyousuf
    Description:
        Test content type definition.
-->
<contentTypes  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
   xmlns='http://www.smartitengineering.com/smart-cms/content/content-type-schema'
   xsi:schemaLocation='http://www.smartitengineering.com/smart-cms/content/content-type-schema ../../main/resources/com/smartitengineering/cms/content/content-type-schema.xsd'>
		<contentType namespace="asdfasdf1">
				<name>XYZ</name>
				<type>
						<textual>
								<fields>
										<field>
												<name>x</name>
												<value>
														<integer />
												</value>
										</field>
										<field>
												<name>y</name>
												<value>
														<boolean />
												</value>
										</field>
										<field>
												<name>y</name>
												<value>
														<string>
																<plain />
														</string>
												</value>
										</field>
								</fields>
						</textual>
				</type>
				<status>
						<statusName>draft</statusName>
						<statusName>marketed</statusName>
						<statusName>obselete</statusName>
				</status>
		</contentType>
		<contentType namespace="jpeg">
				<name>RST</name>
				<type>
						<binary>
								<mimeType>image/jpeg</mimeType>
						</binary>
				</type>
				<status>
						<statusName>draft</statusName>
						<statusName>marketed</statusName>
						<statusName>obselete</statusName>
				</status>
		</contentType>
		<contentType namespace="asdfasdf2">
				<name>ABC</name>
				<type>
						<textual>
								<fields>
										<field>
												<name>x</name>
												<value>
														<integer />
												</value>
										</field>
										<field>
												<name>y</name>
												<value>
														<boolean />
												</value>
										</field>
										<field>
												<name>z</name>
												<value>
														<content>
																
														</content>
												</value>
										</field>
										<field>
												<name>a</name>
												<value>
														<content>
																<typeNS>asdfasdf2</typeNS>
																<typeName>XYZ</typeName>
														</content>
												</value>
										</field>
										<field>
												<name>b</name>
												<value>
														<collection>
																<value>
																		<content>
																				<typeNS>asdfasdf1</typeNS>
																				<typeName>XYZ</typeName>
																		</content>
																</value>
														</collection>
												</value>
										</field>
										<field>
												<name>c</name>
												<value>
														<collection>
																<value>
																		<content>
																				<typeNS>asdfasdf1</typeNS>
																				<typeName>XYZ</typeName>
																		</content>
																</value>
																<size>2</size>
														</collection>
												</value>
										</field>
										<field>
												<name>d</name>
												<value>
														<string>
																<xml />
														</string>
												</value>
										</field>
								</fields>
						</textual>
				</type>
				<status>
						<statusName>draft</statusName>
						<statusName>marketed</statusName>
						<statusName>obselete</statusName>
				</status>
		</contentType>
		<contentType namespace="asdfasdf2">
				<name>DEF</name>
				<type>
						<textual>
								<parentTypeNS>asdfasdf2</parentTypeNS>
								<parentTypeName>ABC</parentTypeName>
								<fields>
										<field>
												<name>e</name>
												<value>
														<string>
																<xml />
														</string>
												</value>
										</field>
								</fields>
						</textual>
				</type>
				<status>
						<statusName>draft</statusName>
						<statusName>marketed</statusName>
						<statusName>obselete</statusName>
				</status>
		</contentType>
		<contentType namespace="asdfasdf2">
				<name>png-images</name>
				<type>
						<binary>
								<mimeType>image/png</mimeType>
								<fields>
										<field>
												<name>fileName</name>
												<value>
														<string>
																<plain />
														</string>
												</value>
										</field>
										<field>
												<name>copyright</name>
												<value>
														<string>
																<plain />
														</string>
												</value>
										</field>
								</fields>
						</binary>
				</type>
				<status>
						<statusName>draft</statusName>
						<statusName>marketed</statusName>
						<statusName>obselete</statusName>
				</status>
		</contentType>
</contentTypes>

=== RainerJava/smart-cms/content-spi-impl/src/test/resources/content-type-def-wih-composition.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
 *
 * This is a simple Content Management System (CMS)
 * Copyright (C) 2009  Imran M Yousuf (imyousuf@smartitengineering.com)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->
<!--
    Document   : content-type-def-1.xml
    Created on : September 25, 2009, 1:10 PM
    Author     : imyousuf
    Description:
        Test content type definition.
-->
<contentTypes  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
               xmlns='http://www.smartitengineering.com/smart-cms/content/content-type-schema'
               xsi:schemaLocation='http://www.smartitengineering.com/smart-cms/content/content-type-schema ../../../../content-api-impl/src/main/resources/com/smartitengineering/cms/content/content-type-schema.xsd'>
  <contentType namespace="test">
    <name>Address</name>
    <fields>
      <field>
        <name>street1</name>
        <displayName>Stree (Line 1)</displayName>
        <value>
          <string>
            <mimeType>text/plain</mimeType>
          </string>
        </value>
      </field>
      <field>
        <name>street2</name>
        <displayName>Stree (Line 2)</displayName>
        <value>
          <string>
            <mimeType>text/plain</mimeType>
          </string>
        </value>
      </field>
      <field>
        <name>area</name>
        <displayName>Area/Thana</displayName>
        <value>
          <string>
            <mimeType>text/plain</mimeType>
          </string>
        </value>
      </field>
      <field>
        <name>city</name>
        <displayName>City</displayName>
        <value>
          <string>
            <mimeType>text/plain</mimeType>
          </string>
        </value>
      </field>
      <field>
        <name>district</name>
        <displayName>State/District</displayName>
        <value>
          <string>
            <mimeType>text/plain</mimeType>
          </string>
        </value>
      </field>
      <field>
        <name>zipCode</name>
        <displayName>Postal Code/Zip Code</displayName>
        <value>
          <string>
            <mimeType>text/plain</mimeType>
          </string>
        </value>
      </field>
      <field>
        <name>country</name>
        <displayName>Country</displayName>
        <value>
          <string>
            <mimeType>text/plain</mimeType>
          </string>
        </value>
      </field>
    </fields>
  </contentType>               
  <contentType namespace="test">
    <name>Order</name>
    <fields>
      <field>
        <name>shippingAddress</name>
        <displayName>Shipping Address</displayName>
        <value>
          <composition>
            <content>
              <definition>
                <typeNS>test</typeNS>
                <typeName>Address</typeName>
              </definition>
            </content>
            <field>
              <name>authorizedPersonnel</name>
              <displayName>Authorized Personnel</displayName>
              <value>
                <string>
                  <mimeType>text/plain</mimeType>
                </string>
              </value>
            </field>
            <field>
              <name>phones</name>
              <displayName>Phone No.</displayName>
              <value>
                <collection>
                  <simple-value>
                    <composition>
                      <field>
                        <name>Number</name>
                        <value>
                          <string>
                            <mimeType>text/plain</mimeType>
                          </string>
                        </value>
                      </field>
                      <field>
                        <name>availability</name>
                        <displayName>Availability</displayName>
                        <value>
                          <composition>
                            <field>
                              <name>from</name>
                              <displayName>Available From</displayName>
                              <value>
                                <datetime></datetime>
                              </value>
                            </field>
                            <field>
                              <name>To</name>
                              <displayName>Available Until</displayName>
                              <value>
                                <datetime></datetime>
                              </value>
                            </field>
                          </composition>
                        </value>
                      </field>
                    </composition>
                  </simple-value>
                </collection>
              </value>
            </field>
          </composition>
        </value>
      </field>
    </fields>
  </contentType>
</contentTypes>

=== RainerJava/smart-cms/smart-cms-client-impl/src/test/resources/content-type-def-shopping.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
 *
 * This is a simple Content Management System (CMS)
 * Copyright (C) 2009  Imran M Yousuf (imyousuf@smartitengineering.com)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->
<!--
    Document   : content-type-def-product.xml
    Created on : September 25, 2009, 5:20 PM
    Author     : imyousuf
    Description:
        A sample content type definition in context of smart shopping
-->
<contentTypes xmlns="http://www.smartitengineering.com/smart-cms/content/content-type-schema"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://www.smartitengineering.com/smart-cms/content/content-type-schema http://github.com/smart-it/smart-cms/raw/master/content-api-impl/src/main/resources/com/smartitengineering/cms/content/content-type-schema.xsd">

  <contentType namespace="com.smartitengineering.smart-shopping.content">
    <name>Book</name>
    <primaryField>isbn</primaryField>
    <fields>
      <field>
        <name>isbn</name>
        <value>
          <string>
            <mimeType>text/plain</mimeType>
          </string>
        </value>
        <required>true</required>
        <variations>
          <variation>
            <name>avar</name>
            <mimeType>some/type</mimeType>
            <uri>
              <external>http://some/uri</external>
            </uri>
          </variation>
          <variation>
            <name>anothervar</name>
            <mimeType>some/type</mimeType>
            <uri>
              <internal>
                <name>internalvar</name>
              </internal>
            </uri>
          </variation>
        </variations>
        <search>
          <index>true</index>
          <store>false</store>
          <boost>a</boost>
        </search>
      </field>
      <field>
        <name>publishers</name>
        <value>
          <collection>
            <simple-value>
              <content>
                <definition>
                  <typeNS>com.smartitengineering.smart-shopping.content</typeNS>
                  <typeName>Publisher</typeName>
                </definition>
              </content>
            </simple-value>
            <maxSize>30</maxSize>
          </collection>
        </value>
        <required>true</required>
        <variations>
          <variation>
            <name>avar</name>
            <mimeType>some/type</mimeType>
            <uri>
              <external>http://some/uri</external>
            </uri>
          </variation>
          <variation>
            <name>anothervar</name>
            <mimeType>some/type</mimeType>
            <uri>
              <internal>
                <name>internalvar</name>
              </internal>
            </uri>
          </variation>
        </variations>
      </field>
      <field>
        <name>authors</name>
        <value>
          <collection>
            <simple-value>
              <content>
                <definition>
                  <typeNS>com.smartitengineering.smart-shopping.content</typeNS>
                  <typeName>Author</typeName>
                </definition>
              </content>
            </simple-value>
          </collection>
        </value>
        <required>true</required>
        <variations>
          <variation>
            <name>avar</name>
            <mimeType>some/type</mimeType>
            <uri>
              <external>http://some/uri</external>
            </uri>
          </variation>
          <variation>
            <name>anothervar</name>
            <mimeType>some/type</mimeType>
            <uri>
              <internal>
                <name>internalvar</name>
              </internal>
            </uri>
          </variation>
        </variations>
      </field>
    </fields>
    <status>
      <statusName>draft</statusName>
      <statusName>marketed</statusName>
      <statusName>obselete</statusName>
    </status>
    <representations>
      <representation>
        <name>arep</name>
        <mimeType>some/type</mimeType>
        <uri>
          <external>http://some/uri</external>
        </uri>
      </representation>
      <representation>
        <name>anotherrep</name>
        <mimeType>some/type</mimeType>
        <uri>
          <internal>
            <name>internalrep</name>
          </internal>
        </uri>
      </representation>
    </representations>
  </contentType>

  <contentType namespace="com.smartitengineering.smart-shopping.content">
    <name>Publisher</name>
    <parent>
      <typeNS>com.smartitengineering.smart-shopping.content</typeNS>
      <typeName>Book</typeName>
    </parent>
    <fields>
      <field>
        <name>name</name>
        <value>
          <string>
            <mimeType>text/plain</mimeType>
          </string>
        </value>
        <variations>
          <variation>
            <name>avar</name>
            <mimeType>some/type</mimeType>
            <uri>
              <external>http://some/uri</external>
            </uri>
          </variation>
          <variation>
            <name>anothervar</name>
            <mimeType>some/type</mimeType>
            <uri>
              <internal>
                <name>internalvar</name>
              </internal>
            </uri>
          </variation>
        </variations>
      </field>
    </fields>
    <status>
      <statusName>draft</statusName>
      <statusName>marketed</statusName>
      <statusName>obselete</statusName>
    </status>
    <representations>
      <representation>
        <name>arep</name>
        <mimeType>some/type</mimeType>
        <uri>
          <external>http://some/uri</external>
        </uri>
      </representation>
      <representation>
        <name>anotherrep</name>
        <mimeType>some/type</mimeType>
        <uri>
          <internal>
            <name>internalrep</name>
          </internal>
        </uri>
      </representation>
    </representations>
  </contentType>

  <contentType namespace="com.smartitengineering.smart-shopping.content">
    <name>Author</name>
    <parent>
      <typeNS>com.smartitengineering.smart-shopping.content</typeNS>
      <typeName>Book</typeName>
    </parent>
    <fields>
      <field>
        <name>name</name>
        <value>
          <string>
            <mimeType>text/plain</mimeType>
          </string>
        </value>
        <variations>
          <variation>
            <name>avar</name>
            <mimeType>some/type</mimeType>
            <uri>
              <external>http://some/uri</external>
            </uri>
          </variation>
          <variation>
            <name>anothervar</name>
            <mimeType>some/type</mimeType>
            <uri>
              <internal>
                <name>internalvar</name>
              </internal>
            </uri>
          </variation>
        </variations>
      </field>
      <field>
        <name>books</name>
        <value>
          <collection>
            <simple-value>
              <content>
                <definition>
                  <typeNS>com.smartitengineering.smart-shopping.content</typeNS>
                  <typeName>Book</typeName>
                </definition>
                <bidirectional>authors</bidirectional>
              </content>
            </simple-value>
          </collection>
        </value>
        <variations>
          <variation>
            <name>avar</name>
            <mimeType>some/type</mimeType>
            <uri>
              <external>http://some/uri</external>
            </uri>
          </variation>
          <variation>
            <name>anothervar</name>
            <mimeType>some/type</mimeType>
            <uri>
              <internal>
                <name>internalvar</name>
              </internal>
            </uri>
          </variation>
        </variations>
      </field>
    </fields>
    <status>
      <statusName>draft</statusName>
      <statusName>published</statusName>
    </status>
  </contentType>
</contentTypes>
