=== RainerJava/smart-cms/content-api/src/main/resources/com/smartitengineering/cms/content/content-type-schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
 *
 * This is a simple Content Management System (CMS)
 * Copyright (C) 2009  Imran M Yousuf (imyousuf@smartitengineering.com)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
xmlns:cur="http://www.smartitengineering.com/smart-cms/content/content-type-schema"
targetNamespace="http://www.smartitengineering.com/smart-cms/content/content-type-schema"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.w3.org/2001/XMLSchema http://www.w3.org/2001/XMLSchema.xsd"
>
		<xs:simpleType name="smartDate">
				<xs:restriction base="xs:dateTime">
						<xs:pattern value="[1-9][0-9]{3}-[0-9]{2}-[0-9]{2}T[0-2][0-9]:[0-5][0-9]:[0-5][0-9]([+-][0-2][0-9]:[0-5][0-9])"/>
				</xs:restriction>
		</xs:simpleType>
		<xs:group name="contentTypeGrp">
				<xs:sequence>
						<xs:element name="typeNS" type="xs:string" />
						<xs:element name="typeName" type="xs:string" />
				</xs:sequence>
		</xs:group>
		<xs:complexType name="value">
				<xs:sequence>
						<xs:choice>
								<xs:element name="content" minOccurs="1" maxOccurs="1">
										<xs:complexType>
												<xs:sequence>
														<xs:group ref="cur:contentTypeGrp" minOccurs="0" maxOccurs="1" />
												</xs:sequence>
										</xs:complexType>
								</xs:element>
								<xs:element name="long" minOccurs="1" maxOccurs="1" />
								<xs:element name="integer" minOccurs="1" maxOccurs="1" />
								<xs:element name="double" minOccurs="1" maxOccurs="1" />
								<xs:element name="boolean" minOccurs="1" maxOccurs="1" />
								<xs:element name="datetime" minOccurs="1" maxOccurs="1" />
								<xs:element name="string" minOccurs="1" maxOccurs="1">
										<xs:complexType>
												<xs:sequence>
														<xs:choice>
																<xs:element name="plain" minOccurs="1" maxOccurs="1"/>
																<xs:element name="xml" minOccurs="1" maxOccurs="1"/>
														</xs:choice>
												</xs:sequence>
										</xs:complexType>
								</xs:element>
								<xs:element name="collection" minOccurs="1" maxOccurs="1">
										<xs:complexType>
												<xs:sequence>
														<xs:element name="item" type="cur:value" minOccurs="1" maxOccurs="1"/>
														<xs:element name="size" type="xs:integer" minOccurs="0" maxOccurs="1"/>
												</xs:sequence>
										</xs:complexType>
								</xs:element>
						</xs:choice>
				</xs:sequence>
		</xs:complexType>
		<xs:complexType name="fields">
				<xs:sequence>
						<xs:element name="field" minOccurs="1" maxOccurs="unbounded">
								<xs:complexType>
										<xs:sequence>
												<xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1"/>
												<xs:element name="value" type="cur:value" minOccurs="1" maxOccurs="1"/>
										</xs:sequence>
								</xs:complexType>
						</xs:element>
				</xs:sequence>
		</xs:complexType>
		<xs:group name="parentType">
				<xs:sequence>
						<xs:element name="parentTypeNS" type="xs:string" />
						<xs:element name="parentTypeName" type="xs:string" />
				</xs:sequence>
		</xs:group>
		<xs:complexType name="textual">
				<xs:sequence>
						<xs:group ref="cur:parentType" minOccurs="0" maxOccurs="1" />
						<xs:element name="fields" type="cur:fields" minOccurs="1" maxOccurs="1" />
				</xs:sequence>
		</xs:complexType>
		<xs:complexType name="binary">
				<xs:sequence>
						<xs:element name="mimeType" type="xs:string" minOccurs="1" maxOccurs="1" />
						<xs:element name="fields" type="cur:fields" minOccurs="0" maxOccurs="1" />
				</xs:sequence>
		</xs:complexType>
		<xs:complexType name="contentType">
				<xs:sequence>
						<xs:element name="name" type="xs:string"/>
						<xs:element name="type">
								<xs:complexType>
										<xs:sequence>
												<xs:choice>
														<xs:element name="textual" type="cur:textual"></xs:element>
														<xs:element name="binary" type="cur:binary"></xs:element>
												</xs:choice>
										</xs:sequence>
								</xs:complexType>
						</xs:element>
				</xs:sequence>
				<xs:attribute name="namespace" type="xs:string" use="required" />
		</xs:complexType>
		<xs:element name="contentTypes">
				<xs:complexType>
						<xs:sequence>
								<xs:element name="contentType" type="cur:contentType" minOccurs="1" maxOccurs="unbounded" />
						</xs:sequence>
				</xs:complexType>
		</xs:element>
</xs:schema>

=== RainerJava/smart-cms/content-api/src/test/resources/content-type-def-shopping.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
 *
 * This is a simple Content Management System (CMS)
 * Copyright (C) 2009  Imran M Yousuf (imyousuf@smartitengineering.com)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->
<!--
    Document   : content-type-def-product.xml
    Created on : September 25, 2009, 5:20 PM
    Author     : imyousuf
    Description:
        A sample content type definition in context of smart shopping
-->
<ns:contentTypes  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
   xmlns:ns='http://www.smartitengineering.com/smart-cms/content/content-type-schema'
   xsi:schemaLocation='http://www.smartitengineering.com/smart-cms/content/content-type-schema ../../main/resources/com/smartitengineering/cms/content/content-type-schema.xsd'>
		<contentType namespace="com.smartitengineering.smart-shopping.content">
				<name>Product</name>
				<type>
						<textual>
								<fields>
										<field>
												<name>manufactureID</name>
												<value>
														<string>
																<plain />
														</string>
												</value>
												<required>true</required>
										</field>
										<field>
												<name>name</name>
												<value>
														<string>
																<plain />
														</string>
												</value>
												<required>true</required>
										</field>
										<field>
												<name>description</name>
												<value>
														<string>
																<xml />
														</string>
												</value>
										</field>
								</fields>
						</textual>
				</type>
				<status>
						<value>draft</value>
						<value>marketed</value>
						<value>withdrawn</value>
						<value>obselete</value>
				</status>
		</contentType>

		<contentType namespace="com.smartitengineering.smart-shopping.content">
				<name>Book</name>
				<type>
						<textual>
								<parentTypeNS>com.smartitengineering.smart-shopping.content</parentTypeNS>
								<parentTypeName>Product</parentTypeName>
								<fields>
										<field>
												<name>isbn</name>
												<value>
														<string>
																<plain />
														</string>
												</value>
												<required>true</required>
										</field>
										<field>
												<name>publishers</name>
												<value>
														<collection>
																<item>
																		<content>
																				<typeNS>com.smartitengineering.smart-shopping.content</typeNS>
																				<typeName>Publisher</typeName>
																		</content>
																</item>
														</collection>
												</value>
												<required>true</required>
										</field>
										<field>
												<name>authors</name>
												<value>
														<collection>
																<item>
																		<content>
																				<typeNS>com.smartitengineering.smart-shopping.content</typeNS>
																				<typeName>Author</typeName>
																		</content>
																</item>
														</collection>
												</value>
												<required>true</required>
										</field>
								</fields>
						</textual>
				</type>
				<status>
						<value>draft</value>
						<value>marketed</value>
						<value>obselete</value>
				</status>
		</contentType>

		<contentType namespace="com.smartitengineering.smart-shopping.content">
				<name>Publisher</name>
				<type>
						<textual>
								<fields>
										<field>
												<name>name</name>
												<value>
														<string>
																<plain />
														</string>
												</value>
												<required>true</required>
										</field>
										<field>
												<name>publicationHouse</name>
												<value>
														<content>
																<typeNS>com.smartitengineering.smart-shopping.content</typeNS>
																<typeName>PublicationHouse</typeName>
														</content>
												</value>
												<required>true</required>
										</field>
								</fields>
						</textual>
				</type>
				<status>
						<value>draft</value>
						<value>marketed</value>
						<value>obselete</value>
				</status>
		</contentType>

		<contentType namespace="com.smartitengineering.smart-shopping.content">
				<name>PublicationHouse</name>
				<type>
						<textual>
								<fields>
										<field>
												<name>name</name>
												<value>
														<string>
																<plain />
														</string>
												</value>
												<required>true</required>
										</field>
										<field>
												<name>adress</name>
												<value>
														<content>
																<typeNS>com.smartitengineering.smart-shopping.content</typeNS>
																<typeName>Address</typeName>
														</content>
												</value>
												<required>true</required>
										</field>
								</fields>
						</textual>
				</type>
				<status>
						<value>draft</value>
						<value>marketed</value>
						<value>obselete</value>
				</status>
		</contentType>

		<contentType namespace="com.smartitengineering.smart-shopping.content">
				<name>Address</name>
				<type>
						<textual>
								<fields>
										<field>
												<name>streetAddress</name>
												<value>
														<string>
																<plain />
														</string>
												</value>
										</field>
										<field>
												<name>state</name>
												<value>
														<string>
																<plain />
														</string>
												</value>
										</field>
										<field>
												<name>city</name>
												<value>
														<string>
																<plain />
														</string>
												</value>
										</field>
										<field>
												<name>country</name>
												<value>
														<string>
																<plain />
														</string>
												</value>
										</field>
										<field>
												<name>zipCode</name>
												<value>
														<string>
																<plain />
														</string>
												</value>
										</field>
								</fields>
						</textual>
				</type>
				<status>
						<value>published</value>
				</status>
		</contentType>
		
		<contentType namespace="com.smartitengineering.smart-shopping.content">
				<name>Author</name>
				<type>
						<textual>
								<fields>
										<field>
												<name>name</name>
												<value>
														<string>
																<plain />
														</string>
												</value>
										</field>										
								</fields>
						</textual>
				</type>
				<status>
						<value>draft</value>
						<value>published</value>
				</status>
		</contentType>
</ns:contentTypes>
